--- 
before_script: 
  - "autopep8 -ir *"
  - "flake8 --max-complexity=10 --exclude=*.txt,*.md,*.pyc *"

install: "pip install -r requerimientos.txt"
language: python
python: 
  - "2.7"
script: 
  - "python TestAreas.py"
  - "coverage run --branch TestAreas.py"
  - "cd tests"
  - "lettuce"
